name: "Terraform plan"

concurrency: terraform-ci

on:
  issue_comment:
    types: [created]

jobs:
  terraform-plan:
    name: "Terraform plan"
    if: >
      github.event.issue.pull_request
    runs-on: ubuntu-latest
    env:
      # Swift state backend
      OS_USERNAME: ${{ secrets.OS_USERNAME }}
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_TENANT_NAME: ${{ secrets.OS_TENANT_NAME }}
      # GitHub provider
      TF_VAR_app_node_id: ${{ secrets.TF_VAR_APP_NODE_ID }}
      TF_VAR_github_app_id: ${{ secrets.GH_APP_ID }}
      TF_VAR_github_app_installation_id: ${{ secrets.GH_APP_INSTALLATION_ID }}
      TF_VAR_github_app_pem_file: ${{ secrets.GH_APP_PEM_FILE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.issue.pull_request.head.repo.full_name }}
          ref: ${{ github.event.issue.pull_request.head.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - uses: actions/github-script@0.9.0
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style \`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization \`${{ steps.init.outcome }}\`
            #### Terraform Validation \`${{ steps.validate.outcome }}\`
            #### Terraform Plan \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
