name: "Terraform checks"

on:
  pull_request:
    paths-ignore:
      - .gitignore
      - "*.md"
      - CODEOWNERS
    branches:
      - main

jobs:
  terraform-checks:
    name: "Terraform checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend=false
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
