name: "Terraform apply"

concurrency: terraform-ci

on:
  push:
    paths-ignore:
      # YAML anchors doesn't seem to work in GitHub Actions, so we have to copy
      # this field.
      - .gitignore
      - "*.md"
      - CODEOWNERS
    branches:
      - main

jobs:
  terraform-apply:
    name: "Terraform apply"
    runs-on: ubuntu-latest
    env:
      # Swift state backend
      OS_USERNAME: ${{ secrets.OS_USERNAME }}
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_TENANT_NAME: ${{ secrets.OS_TENANT_NAME }}
      # GitHub provider
      TF_VAR_app_node_id: ${{ secrets.TF_VAR_APP_NODE_ID }}
      TF_VAR_github_app_id: ${{ secrets.GH_APP_ID }}
      TF_VAR_github_app_installation_id: ${{ secrets.GH_APP_INSTALLATION_ID }}
      TF_VAR_github_app_pem_file: ${{ secrets.GH_APP_PEM_FILE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
